### PR TITLE
feat: support linux

### LINKED ISSUE #1: Support linux font installation

### PR DESCRIPTION
**Pull request by z7pz**

### CODE REVIEW

**Comment by z7pz** [comment]
can anyone try it on linux machine and tell me if it works?

**Comment by z7pz** [comment]
@abdulrahman1s

**Comment by abdulrahman1s** [comment]
Fonts are installable on Linux bruuh..
I'll look into this today.

**Comment by z7pz** [comment]
> Fonts are installable on Linux bruuh.. I'll look into this today.

who said it's not installable... 
i just want to check if it works

**Pull request merged**
